name: smiring_database
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.3+1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3

  # Routing
  go_router: ^17.0.1

  # State management
  hooks_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # Backend
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/